[package]
name = "orzma_vt"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
vtparse = { version = "0.7.0" }
unicode-width = { version = "0.2" }
alacritty_terminal = { version = "0.26", optional = true }
thiserror = { workspace = true }

[lints]
workspace = true

[features]
default = ["alacritty"]
alacritty = ["dep:alacritty_terminal"]
