[package]
name = "orzma_vt"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bitflags = { workspace = true }
vtparse = { version = "0.7.0" }

[lints]
workspace = true
