[package]
name = "orzmd"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
publish.workspace = true

[[bin]]
name = "orzmd"
path = "src/main.rs"

[dependencies]
ratatui_orzma = { path = "../../sdk/ratatui_orzma" }
ratatui = "0.29"
serde = { workspace = true }
anyhow = { workspace = true }
notify-debouncer-full = "0.3"
rust-embed = { version = "8", features = ["deterministic-timestamps"] }
tempfile = { workspace = true }
blake3 = "1"
open = { workspace = true }

[target.'cfg(windows)'.dependencies]
dunce = "1"

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
