[package]
name = "bevy_orzma_terminal"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bevy = { workspace = true }
orzma_vt = { path = "../orzma_vt" }
orzma_terminal = { path = "../orzma_terminal" }

[lints]
workspace = true
