#!/usr/bin/env bash
# capture-nvim-tape.sh: Capture nvim PTY output as an OZTAPE-format tape.
# Linux-only (uses Python stdlib `pty` module). macOS contributors should
# use the pre-committed binary tape generated by a Linux maintainer.
set -euo pipefail

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "error: capture-nvim-tape.sh is Linux-only (Python pty + scripted nvim)." >&2
    echo "macOS contributors: use the committed binary tape if present, or" >&2
    echo "rely on synthetic_scroll_burst.tape (no nvim required)." >&2
    exit 2
fi

if ! command -v nvim >/dev/null 2>&1; then
    echo "error: nvim not found on PATH. Install nvim >= 0.10.0 to capture a tape." >&2
    exit 2
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 not found on PATH. Install Python 3 (stdlib \`pty\` required)." >&2
    exit 2
fi

NVIM_MIN_VERSION="0.10.0"
NVIM_VER=$(nvim --version | head -1 | awk '{print $2}' | sed 's/^v//')

OUTPUT="${1:-daemon/terminal/tests/fixtures/pty_tapes/nvim_ctrl_d_1k_lines.tape}"
INPUT_FILE=$(mktemp /tmp/ozmux-tape-input.XXXXXXXXXX.txt)
trap 'rm -f "$INPUT_FILE"' EXIT

# Generate 1000-line input file
seq 1 1000 | awk '{printf "line %04d\n", $0}' > "$INPUT_FILE"

# Use Python pty to spawn nvim, send <C-d> 100 times, then :q!
python3 << PYEOF
import os, pty, time, struct, sys, termios, fcntl

INPUT_FILE = "$INPUT_FILE"
OUTPUT     = "$OUTPUT"

def main():
    pid, fd = pty.fork()
    if pid == 0:
        os.environ['TERM'] = 'xterm-256color'
        os.environ['LANG'] = 'en_US.UTF-8'
        os.environ['LC_ALL'] = 'en_US.UTF-8'
        os.execlp('nvim', 'nvim', '--clean',
                  '--cmd', 'set lines=40 columns=120 nowrap',
                  INPUT_FILE)
    # parent: set PTY size, drive nvim
    winsize = struct.pack("HHHH", 40, 120, 0, 0)
    fcntl.ioctl(fd, termios.TIOCSWINSZ, winsize)

    records = []
    start_ns = time.monotonic_ns()
    captured = bytearray()

    # Wait for initial render
    time.sleep(0.5)
    while True:
        try:
            data = os.read(fd, 65536)
        except OSError:
            break
        if not data:
            break
        ts_ns = time.monotonic_ns() - start_ns
        records.append((ts_ns, bytes(data)))
        captured.extend(data)
        if len(captured) > 16384:
            break

    # Send <C-d> (0x04) 100 times with 50ms gaps
    for _ in range(100):
        os.write(fd, b'\x04')
        time.sleep(0.05)
        try:
            data = os.read(fd, 65536)
            if data:
                ts_ns = time.monotonic_ns() - start_ns
                records.append((ts_ns, bytes(data)))
        except OSError:
            break

    # Quit nvim
    os.write(fd, b':q!\n')
    time.sleep(0.5)
    try:
        data = os.read(fd, 65536)
        if data:
            ts_ns = time.monotonic_ns() - start_ns
            records.append((ts_ns, bytes(data)))
    except OSError:
        pass

    # Write OZTAPE-format file
    with open(OUTPUT, 'wb') as f:
        f.write(b'OZTAPE\x00\x00')
        f.write(struct.pack('<H', 1))
        f.write(b'\x00' * 6)
        for ts, data in records:
            f.write(struct.pack('<I', len(data)))
            f.write(struct.pack('<Q', ts))
            f.write(data)
        f.write(struct.pack('<I', 0xFFFFFFFF))
    print(f'capture-nvim-tape.sh: wrote {len(records)} records to {OUTPUT}', file=sys.stderr)

main()
PYEOF

SHA=$(sha256sum "$OUTPUT" | awk '{print $1}')
MANIFEST="${OUTPUT%.tape}.manifest.toml"

cat > "$MANIFEST" <<MANIFEST_EOF
sha256 = "$SHA"
estimated_total_wire_messages = 500
created_kind = "real"
created_at = "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

[runtime]
alacritty_terminal_version = "0.26.0"

[real]
terminal_cols = 120
terminal_rows = 40
env_term = "xterm-256color"
env_lang = "en_US.UTF-8"
env_lc_all = "en_US.UTF-8"
nvim_version_captured = "$NVIM_VER"
nvim_min_version = "$NVIM_MIN_VERSION"
nvim_clean_mode = true
capture_script = "scripts/capture-nvim-tape.sh"
captured_on = "$(uname -srm)"
MANIFEST_EOF

echo "capture-nvim-tape.sh: wrote $OUTPUT + $MANIFEST" >&2
