#!/usr/bin/env python3
"""Generate licenses/THIRD-PARTY-LICENSES.md aggregating all third-party licenses.

Sections, in fixed order: Rust crates (cargo-about), npm packages
(@quantco/pnpm-licenses, scoped to @ozma/ozmd-web prod deps), bundled fonts,
and CEF/Chromium. Output is deterministic so CI can detect drift.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LICENSES_DIR = REPO_ROOT / "licenses"
OUTPUT_PATH = LICENSES_DIR / "THIRD-PARTY-LICENSES.md"
NPM_DIR = REPO_ROOT / "apps" / "ozmd"
FENCE = "~~~"

HEADER = (
    "# Third-Party Licenses\n"
    "\n"
    "This file is generated by `just licenses` (scripts/generate_licenses.py).\n"
    "Do not edit it by hand.\n"
    "\n"
    "ozmux bundles the third-party software listed below; each entry reproduces\n"
    "the upstream license text in full.\n"
)


def _fenced(text: str) -> str:
    body = text.strip("\n")
    fence_len = len(FENCE)
    for line in body.split("\n"):
        stripped = line.strip()
        if stripped and set(stripped) == {"~"}:
            fence_len = max(fence_len, len(stripped) + 1)
    fence = "~" * fence_len
    return f"{fence}text\n{body}\n{fence}\n"


def render_rust_section(rust_body: str) -> str:
    return "## Rust crates (Cargo dependencies)\n\n" + rust_body.strip("\n") + "\n"


def render_npm_section(entries: list[dict]) -> str:
    lines = ["## npm packages (@ozma/ozmd-web runtime dependencies)\n"]
    for entry in sorted(entries, key=lambda e: (e["name"], e.get("version", ""))):
        license_id = entry.get("license") or "UNKNOWN"
        text = entry.get("licenseText") or entry.get("additionalText")
        if not text:
            homepage = entry.get("homepage") or "the upstream repository"
            text = f"(No license text was provided by the package; see {homepage}.)"
        version = entry.get("version", "")
        title = f"{entry['name']} {version}" if version else entry["name"]
        lines.append(f"### {title} — {license_id}\n")
        lines.append(_fenced(text))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_fonts_section(licenses_dir: Path) -> str:
    lines = ["## Bundled fonts\n"]
    vendors = sorted(
        p for p in licenses_dir.iterdir() if p.is_dir() and p.name != "chromium"
    )
    for vendor in vendors:
        for license_file in sorted(f for f in vendor.iterdir() if f.is_file()):
            lines.append(f"### {vendor.name}/{license_file.name}\n")
            lines.append(_fenced(license_file.read_text(encoding="utf-8")))
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_chromium_section(licenses_dir: Path) -> str:
    chromium = licenses_dir / "chromium"
    license_text = (chromium / "LICENSE.txt").read_text(encoding="utf-8")
    lines = [
        "## CEF / Chromium\n",
        "ozmux bundles the Chromium Embedded Framework. Its license follows. The\n"
        "complete Chromium third-party credits ship alongside this file as\n"
        "`chromium/CREDITS.html` (also copied into the app bundle).\n",
        _fenced(license_text),
    ]
    return "\n".join(lines).rstrip("\n") + "\n"


def assemble(rust_body: str, npm_entries: list[dict], licenses_dir: Path) -> str:
    parts = [
        HEADER,
        render_rust_section(rust_body),
        render_npm_section(npm_entries),
        render_fonts_section(licenses_dir),
        render_chromium_section(licenses_dir),
    ]
    return "\n".join(part.rstrip("\n") for part in parts) + "\n"


def run_cargo_about(version: str = "0.9.0") -> str:
    template = REPO_ROOT / "about.hbs"
    result = subprocess.run(
        [
            "cargo", "about", "generate",
            "--frozen", "--workspace", "--all-features", "--fail",
            str(template),
        ],
        cwd=REPO_ROOT, capture_output=True, text=True, encoding="utf-8",
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(
            "cargo-about failed. Install the pinned version with "
            f"`cargo install cargo-about@{version} --locked --features cli` and resolve "
            "any unsatisfied licenses in about.toml."
        )
    return result.stdout


def _run_checked(argv: list[str], cwd: Path, stdin: str | None = None) -> str:
    try:
        return subprocess.run(
            argv, cwd=cwd, input=stdin,
            capture_output=True, text=True, encoding="utf-8", check=True,
        ).stdout
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.stderr or "")
        sys.stderr.write(exc.stdout or "")
        raise


def run_pnpm_licenses(version: str) -> list[dict]:
    listed = _run_checked(["pnpm", "licenses", "list", "--prod", "--json"], NPM_DIR)
    with tempfile.TemporaryDirectory() as tmp:
        inp_path = Path(tmp) / "input.json"
        out_path = Path(tmp) / "output.json"
        inp_path.write_text(listed, encoding="utf-8")
        _run_checked(
            [
                "pnpm", "dlx", f"@quantco/pnpm-licenses@{version}",
                "list", "--json-input-file", str(inp_path), "--output-file", str(out_path),
            ],
            REPO_ROOT,
        )
        return json.loads(out_path.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Generate THIRD-PARTY-LICENSES.md")
    parser.add_argument("--cargo-about-version", default="0.9.0")
    parser.add_argument("--pnpm-licenses-version", default="2.4.2")
    args = parser.parse_args(argv)

    rust_body = run_cargo_about(args.cargo_about_version)
    npm_entries = run_pnpm_licenses(args.pnpm_licenses_version)
    content = assemble(rust_body, npm_entries, LICENSES_DIR)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(npm_entries)} npm packages)")


if __name__ == "__main__":
    main()
