#!/usr/bin/env python3
"""Generate licenses/THIRD-PARTY-LICENSES.md aggregating all third-party licenses.

Sections, in fixed order: Rust crates (cargo-about), npm packages
(@quantco/pnpm-licenses, scoped to @ozma/ozmd-web prod deps), bundled fonts,
and CEF/Chromium. Output is deterministic so CI can detect drift.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LICENSES_DIR = REPO_ROOT / "licenses"
OUTPUT_PATH = LICENSES_DIR / "THIRD-PARTY-LICENSES.md"
NPM_DIR = REPO_ROOT / "apps" / "ozmd"
FENCE = "~~~"

HEADER = (
    "# Third-Party Licenses\n"
    "\n"
    "This file is generated by `just licenses` (scripts/generate_licenses.py).\n"
    "Do not edit it by hand.\n"
    "\n"
    "ozmux bundles the third-party software listed below; each entry reproduces\n"
    "the upstream license text in full.\n"
)


def _fenced(text: str) -> str:
    body = text.strip("\n")
    return f"{FENCE}text\n{body}\n{FENCE}\n"


def render_rust_section(rust_body: str) -> str:
    return "## Rust crates (Cargo dependencies)\n\n" + rust_body.strip("\n") + "\n"


def render_npm_section(entries: list[dict]) -> str:
    lines = ["## npm packages (@ozma/ozmd-web runtime dependencies)\n"]
    for entry in sorted(entries, key=lambda e: (e["name"], e.get("version", ""))):
        license_id = entry.get("license") or "UNKNOWN"
        text = entry.get("licenseText") or entry.get("additionalText")
        if not text:
            homepage = entry.get("homepage") or "the upstream repository"
            text = f"(No license text was provided by the package; see {homepage}.)"
        lines.append(f"### {entry['name']} {entry.get('version', '')} — {license_id}\n")
        lines.append(_fenced(text))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_fonts_section(licenses_dir: Path) -> str:
    lines = ["## Bundled fonts\n"]
    vendors = sorted(
        p for p in licenses_dir.iterdir() if p.is_dir() and p.name != "chromium"
    )
    for vendor in vendors:
        for license_file in sorted(f for f in vendor.iterdir() if f.is_file()):
            lines.append(f"### {vendor.name}/{license_file.name}\n")
            lines.append(_fenced(license_file.read_text(encoding="utf-8")))
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_chromium_section(licenses_dir: Path) -> str:
    chromium = licenses_dir / "chromium"
    license_text = (chromium / "LICENSE.txt").read_text(encoding="utf-8")
    lines = [
        "## CEF / Chromium\n",
        "ozmux bundles the Chromium Embedded Framework. Its license follows. The\n"
        "complete Chromium third-party credits ship alongside this file as\n"
        "`chromium/CREDITS.html` (also copied into the app bundle).\n",
        _fenced(license_text),
    ]
    return "\n".join(lines).rstrip("\n") + "\n"


def assemble(rust_body: str, npm_entries: list[dict], licenses_dir: Path) -> str:
    parts = [
        HEADER,
        render_rust_section(rust_body),
        render_npm_section(npm_entries),
        render_fonts_section(licenses_dir),
        render_chromium_section(licenses_dir),
    ]
    return "\n".join(part.rstrip("\n") for part in parts) + "\n"


def run_cargo_about() -> str:
    template = REPO_ROOT / "about.hbs"
    result = subprocess.run(
        [
            "cargo", "about", "generate",
            "--frozen", "--workspace", "--all-features", "--fail",
            str(template),
        ],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(
            "cargo-about failed. Install the pinned version with "
            "`cargo install cargo-about@0.9.0 --locked --features cli` and resolve any "
            "unsatisfied licenses in about.toml."
        )
    return result.stdout


def run_pnpm_licenses(version: str) -> list[dict]:
    try:
        listed = subprocess.run(
            ["pnpm", "licenses", "list", "--prod", "--json"],
            cwd=NPM_DIR, capture_output=True, text=True, check=True,
        ).stdout
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.stderr or "")
        sys.stderr.write(exc.stdout or "")
        raise
    inp_f = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False)
    try:
        inp_f.write(listed)
        inp_f.close()
        out_fd, out_path = tempfile.mkstemp(suffix=".json")
        os.close(out_fd)
        try:
            try:
                subprocess.run(
                    [
                        "pnpm", "dlx", f"@quantco/pnpm-licenses@{version}",
                        "list", "--json-input-file", inp_f.name, "--output-file", out_path,
                    ],
                    cwd=REPO_ROOT, capture_output=True, text=True, check=True,
                )
            except subprocess.CalledProcessError as exc:
                sys.stderr.write(exc.stderr or "")
                sys.stderr.write(exc.stdout or "")
                raise
            return json.loads(Path(out_path).read_text(encoding="utf-8"))
        finally:
            Path(out_path).unlink(missing_ok=True)
    finally:
        Path(inp_f.name).unlink(missing_ok=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Generate THIRD-PARTY-LICENSES.md")
    parser.add_argument("--pnpm-licenses-version", default="2.4.2")
    args = parser.parse_args(argv)

    rust_body = run_cargo_about()
    npm_entries = run_pnpm_licenses(args.pnpm_licenses_version)
    content = assemble(rust_body, npm_entries, LICENSES_DIR)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(npm_entries)} npm packages)")


if __name__ == "__main__":
    main()
